### ISSUE TITLE
Mention let'y encrypt in README.md

### ISSUE THREAD

**Issue by pableu** [mkjensen/unifi-acme.sh#2]
I'd suggest mentioning let's encrypt in the readme. 

I already googled for a tool like this months ago, but I always searched for stuff like "unifi letsencrypt" and similar and never got to this project. It only recently occurred to me to search for "unifi acme.sh", and now I found this repository and I'm happy :-)

Adding the phrase "let's encrypt" to the readme would improve discoverability of this tool. Search engine optimization, so to speak.

**Comment by mkjensen** [comment]
Excellent suggestion, thanks. Fixed in https://github.com/mkjensen/unifi-acme.sh/commit/3a6d05df9857567ad281f8be85a04a92ac884737.
